neulyferreira/frontend/urls.py
from django.conf.urls import url
from neulyferreira.frontend import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^posts/', views.posts, name='posts'),
    url(r'^post_detail/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail')
]

neulyferreira/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('neulyferreira.frontend.urls', namespace='frontend')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^backend/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

neulyferreira/core/models.py
from django.db import models
# ckeditor
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Category(models.Model):
    title = models.CharField('Título', max_length=250)
    slug = models.SlugField('Atalho')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['-title']


class Post(models.Model):
    title = models.CharField('Título', max_length=250)
    slug = models.SlugField('Atalho')
    content = RichTextUploadingField('Conteúdo', blank=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Categoria')
    author = models.CharField('Autor', max_length=100)
    tags = models.CharField(max_length=80, blank=True)
    published = models.BooleanField(default=True)
    image_capa = models.ImageField(upload_to='posts/images',
                              verbose_name='Imagem da Capa',
                              null=True, blank=True)
    created_at = models.DateTimeField(
        'Criado em', auto_now_add=True
    )
    updated_at = models.DateTimeField(
        'Atualizado em', auto_now=True
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Postagem'
        verbose_name_plural = 'Postagens'
        ordering = ['-title']


class Ad(models.Model):
    title = models.CharField(verbose_name='Nome da Empresa', blank=False, null=False,
                             max_length=250)
    image = models.ImageField(upload_to='anuncios/images',
                              verbose_name='Imagem da Empresa',
                              null=False, blank=False)
    status = models.BooleanField(null=False, blank=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Anúncio de Empresa'
        verbose_name_plural = 'Anúncios de Empresas'
        ordering = ['-title']

class About(models.Model):
    summary = models.CharField(verbose_name='Resumo', blank=False, max_length=250)
    content = RichTextUploadingField(verbose_name='Conteúdo', blank=False)
    image_capa = models.ImageField(upload_to='about/images',
                              verbose_name='Imagem da Capa',
                              null=True, blank=True)

    def __str__(self):
        return self.summary

    class Meta:
        verbose_name = 'Sobre Neuly'
        verbose_name_plural = 'Sobre Neuly'
        ordering = ['-summary']

class Banner(models.Model):
    title = models.CharField(blank=False, max_length=100)
    image_banner = models.ImageField(upload_to='banner/images',
                              verbose_name='Imagem de Início',
                              null=True, blank=True)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Banner Início'
        verbose_name_plural = 'Banner Início'
        ordering = ['-title']

neulyferreira/frontend/models.py
from django.db import models

# Create your models here.

neulyferreira/frontend/forms.py
from django import forms

# our new form
class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    contact_cellphone = forms.CharField(required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

neulyferreira/core/views.py
from django.shortcuts import render

# Create your views here.

neulyferreira/frontend/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
import datetime
from neulyferreira.core.models import Category
from neulyferreira.core.models import Post
from neulyferreira.core.models import Ad
from neulyferreira.core.models import About
from neulyferreira.core.models import Banner
# Create your views here.

def index(request):
    posts = Post.objects.all().filter(published=True).order_by('-created_at')[:3]
    categories = Category.objects.all()
    now = datetime.datetime.now()
    ads = Ad.objects.all()
    recent_posts = Post.objects.filter(published=True).order_by('-created_at')[0:1]
    banner = Banner.objects.all()[:1].get()
    senzala = Ad.objects.all()[:1].get()
    about = About.objects.all()[:1].get()
    template_name = 'posts/index.html'
    context = {
        'posts': posts,
        'categories': categories,
        'year': now.year,
        'ads': ads,
        'senzala': senzala,
        'recent_posts': recent_posts,
        'about': about,
        'banner': banner
    }
    return render(request, template_name, context)


def about(request):
    about = About.objects.get(id=1)
    template_name = 'about/about.html'
    context = {
        'about': about,

    }
    return render(request, template_name, context)


def contact(request):
    about = About.objects.get(id=1)
    template_name = 'contact/contact.html'
    context = {
        'contact': contact

    }
    return render(request, template_name, context)

def posts(request):
    posts_list = Post.objects.all().filter(published=True)
    paginator = Paginator(posts_list, 4)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)
    categories = Category.objects.all()
    now = datetime.datetime.now()
    ads = Ad.objects.all()
    recent_posts = Post.objects.filter(published=True).order_by('-created_at')[0:3]
    senzala = Ad.objects.get(id=1)
    about = About.objects.get(id=1)
    template_name = 'posts/posts.html'
    context = {
        'posts': posts,
        'categories': categories,
        'year': now.year,
        'ads': ads,
        'senzala': senzala,
        'recent_posts': recent_posts,
        'about': about
    }
    return render(request, template_name, context)


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    categories = Category.objects.all()
    now = datetime.datetime.now()
    ads = Ad.objects.all()
    recent_posts = Post.objects.filter(published=True).order_by('-created_at')[0:3]
    senzala = Ad.objects.get(id=1)
    about = About.objects.get(id=1)
    template_name = 'posts/post_detail.html'
    context = {
        'post': post,

        'categories': categories,
        'year': now.year,
        'ads': ads,
        'senzala': senzala,
        'recent_posts': recent_posts,
        'about': about
    }
    return render(request, template_name, context)

neulyferreira/frontend/templates/about/about.html
{% extends 'base.html' %}
{% block main %}

<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <div class="aboutus-img">
            <img src="{{ about.image_capa.url }}" alt="images" />
        </div>
    </div>
    <div class="col-lg-8 col-md-8 ol-sm-8 col-xs-12">
        <div class="aboutus-info">
            <h2>Quem sou?</h2>
            <h5>{{ about.summary }}</h5>
            <p>
              {{ about.content|safe }}
            </p>
            <h3>Neuly Ferreira</h3>
            <!-- Social Media Links Begins -->
            <ul class="social">
                <li>
                    <a href="https://www.facebook.com/neuly.ferreiradasilva"><i class="fa fa-facebook"></i></a>
                </li>

            </ul>
            <!-- Social Media Links Ends -->
        </div>
    </div>
</div>
    {% endblock %}

neulyferreira/frontend/templates/base.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0">
  <!--<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="images/favicon.ico" type="image/x-icon">-->
  <title> Neuly Ferreira </title>
  <!-- Bootstrap css -->
  <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <!-- Owl Carousel css -->
  <link type="text/css" rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <!-- Font Awesome css -->
  <link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
  <!-- Magnific Popup css -->
  <link type="text/css" href="{% static 'css/magnific-popup.css' %}" rel="stylesheet" />
  <!-- Custom css -->
  <link type="text/css" href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- Custom Media Query css -->
  <link type="text/css" href="{% static 'css/media.css' %}" rel="stylesheet" />
</head>

<body id="mainBox" data-spy="scroll" data-target="#main-menu" data-offset="150">
  <div class="blog-main">
    <div id="site-head">
      <!-- Header Section Begins -->
      <header id="header" class="header-block" data-top="0" data-scroll="100">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 main-menu">
              <div class="menuBar scrollbtn">
                <!-- Navigation Menu Begins -->
                <nav class="navbar navbar-default">
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
                                            <span class="sr-only">Toggle navigation</span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                    <!-- Site Logo Begins -->
                    <div class="logo">
                      <a class="navbar-brand" href="{% url 'frontend:index' %}"><img src="{% static 'images/logo.png' %}" alt="logo" /></a>
                    </div>
                    <!-- Site Logo Ends -->
                  </div>
                  <div class="home-menu">
                    <div class="collapse navbar-collapse" id="main-menu">
                      <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'frontend:index' %}l">Início</a></li>
                        <li><a href="{% url 'frontend:posts' %}">Posts</a></li>
                        <li><a href="{% url 'frontend:about' %}">Quem sou eu?</a></li>
                        <li><a href="{% url 'frontend:contact' %}">Fale comigo</a></li>
                      </ul>
                    </div>
                    <!-- Search Form Begins -->
                    <div class="search-form">
                      <form>
                        <div class="form-group">
                          <div class="btn-form"></div>
                          <input type="text" class="form-control" placeholder="Search">
                        </div>
                      </form>
                    </div>
                    <!-- Search Form Ends -->
                  </div>
                </nav>
                <!-- Navigation Menu Ends -->
              </div>
            </div>
          </div>
        </div>
      </header>
      <!-- Header Section Ends -->
      <!-- Banner Section Begins -->
      <br /><br /><br /><br /><br />
      <!-- Banner Section Ends -->
    </div>
    <div class="main">
      <!-- Content Section Begins -->
      {% block main %}{% endblock %}
      <!-- Content Section Ends -->

      <!-- footer Section Begins -->

      <br /><br /><br /><br /><br />
      <footer id="footer" class="footer pr pad-bottom-small text-align-center">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

              <!-- Subscribe Form Begins -->

              <!-- Subscribe Form Ends -->
              <!-- Footer Links Begins -->
              <ul class="footer-links">
                <li> <a href="{% url 'frontend:index' %}">Inicio</a> </li>
                <li> <a href="{% url 'frontend:posts' %}">Posts</a> </li>
                <li> <a href="{% url 'frontend:about' %}">Quem sou?</a> </li>
                <li> <a href="{% url 'frontend:contact' %}">Fale comigo</a> </li>
              </ul>
              <!-- Footer Links Ends -->
              <!-- Social Media Links Begins -->
              <ul class="social">
                <li>
                  <a href="https://www.facebook.com/neuly.ferreiradasilva"><i class="fa fa-facebook"></i></a>
                </li>
                <li>
                  <a href="javascript:void(0)"><i class="fa fa-youtube"></i></a>
                </li>
              </ul>
              <!-- Social Media Links Ends -->
            </div>
          </div>
        </div>
      </footer>
      <!-- footer Section Ends -->
      <!-- Copyright Section Begins -->
      <div id="copyright" class="copyright pr text-align-center">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <h5>&copy; {{ year }} <a href="#">{Neuly Ferreira}</a> desenvolvido por <a href="https://arferreira.github.io/" class="dotstore-link" target="_blank">Antonio Ricardo.</a></h5>
            </div>
          </div>
        </div>
      </div>
      <!-- Copyright Section Ends -->
      <!-- Back to top Section Begins -->
      <a href="javascript:void(0);" class="back-to-top"><i class="fa fa-long-arrow-up" aria-hidden="true"></i></a>
      <!-- Back to top Section Ends -->
    </div>
  </div>

  <!-- Mobile Menu Section Begins -->
  <div class="main_menucontent overlapblackbg"></div>
  <div class="menu-wrap"></div>
  <!-- Mobile Menu Section Ends -->
  <!-- Jquery Js -->
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Bootstrap Js -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- Modernizr Js -->
  <script type="text/javascript" src="{% static 'js/modernizr.js' %}"></script>
  <!-- Owl Carousel Js -->
  <script type="text/javascript" src="{% static 'js/owl.carousel.js' %}"></script>
  <!-- Localscroll Js -->
  <script type="text/javascript" src="{% static 'js/jquery.localscroll-1.2.7-min.js' %}"></script>
  <!-- Imagesloaded Js -->
  <script type="text/javascript" src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
  <!-- Isotope Js -->
  <script type="text/javascript" src="{% static 'js/jquery.isotope.min.js' %}"></script>
  <!-- Parallax Js -->
  <script type="text/javascript" src="{% static 'js/jquery.parallax-1.1.3.js' %}"></script>
  <!-- Magnific Popup Js -->
  <script type="text/javascript" src="{% static 'js/jquery.magnific-popup.js' %}"></script>
  <!-- Custom Js -->
  <script type="text/javascript" src="{% static 'js/element.js' %}"></script>
</body>

</html>

neulyferreira/frontend/templates/base_index.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0">
  <!--<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="images/favicon.ico" type="image/x-icon">-->
  <title> Neuly Ferreira </title>
  <!-- Bootstrap css -->
  <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <!-- Owl Carousel css -->
  <link type="text/css" rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <!-- Font Awesome css -->
  <link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
  <!-- Magnific Popup css -->
  <link type="text/css" href="{% static 'css/magnific-popup.css' %}" rel="stylesheet" />
  <!-- Custom css -->
  <link type="text/css" href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- Custom Media Query css -->
  <link type="text/css" href="{% static 'css/media.css' %}" rel="stylesheet" />
</head>

<body id="mainBox" data-spy="scroll" data-target="#main-menu" data-offset="150">
  <div class="blog-main">
    <div id="site-head">
      <!-- Header Section Begins -->
      <header id="header" class="header-block" data-top="0" data-scroll="100">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 main-menu">
              <div class="menuBar scrollbtn">
                <!-- Navigation Menu Begins -->
                <nav class="navbar navbar-default">
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
                                            <span class="sr-only">Toggle navigation</span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                    <!-- Site Logo Begins -->
                    <div class="logo">
                      <a class="navbar-brand" href="{% url 'frontend:index' %}"><img src="{% static 'images/logo.png' %}" alt="logo" /></a>
                    </div>
                    <!-- Site Logo Ends -->
                  </div>
                  <div class="home-menu">
                    <div class="collapse navbar-collapse" id="main-menu">
                      <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'frontend:index' %}">Início</a></li>
                        <li><a href="{% url 'frontend:posts' %}">Posts</a></li>
                        <li><a href="{% url 'frontend:about' %}">Quem sou eu?</a></li>
                        <li><a href="{% url 'frontend:contact' %}">Fale comigo</a></li>
                      </ul>
                    </div>
                    <!-- Search Form Begins -->
                    <div class="search-form">
                      <form>
                        <div class="form-group">
                          <div class="btn-form"></div>
                          <input type="text" class="form-control" placeholder="Search">
                        </div>
                      </form>
                    </div>
                    <!-- Search Form Ends -->
                  </div>
                </nav>
                <!-- Navigation Menu Ends -->
              </div>
            </div>
          </div>
        </div>
      </header>
      <!-- Header Section Ends -->
      <!-- Banner Section Begins -->
      <section id="banner" class="banner banner-static parallax-fix parallaximg" style="
            background-image: url('{{ banner.image_banner.url }}');">
        <div class="container pr">
          <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

            </div>
          </div>
        </div>
      </section>
      <!-- Banner Section Ends -->
    </div>
    <div class="main">
      <!-- Content Section Begins -->
      {% block main %}{% endblock %}
      <!-- Content Section Ends -->

      <!-- footer Section Begins -->
      <footer id="footer" class="footer pr pad-bottom-small text-align-center">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

              <!-- Subscribe Form Begins -->

              <!-- Subscribe Form Ends -->
              <!-- Footer Links Begins -->
              <ul class="footer-links">
                <li> <a href="{% url 'frontend:index' %}">Inicio</a> </li>
                <li> <a href="{% url 'frontend:posts' %}">Posts</a> </li>
                <li> <a href="{% url 'frontend:about' %}">Quem sou?</a> </li>
                <li> <a href="{% url 'frontend:contact' %}">Fale comigo</a> </li>
              </ul>
              <!-- Footer Links Ends -->
              <!-- Social Media Links Begins -->
              <ul class="social">
                <li>
                  <a href="https://www.facebook.com/neuly.ferreiradasilva"><i class="fa fa-facebook"></i></a>
                </li>
                <li>
                  <a href="javascript:void(0)"><i class="fa fa-youtube"></i></a>
                </li>
              </ul>
              <!-- Social Media Links Ends -->
            </div>
          </div>
        </div>
      </footer>
      <!-- footer Section Ends -->
      <!-- Copyright Section Begins -->
      <div id="copyright" class="copyright pr text-align-center">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <h5>&copy; {{ year }} <a href="#">{Neuly Ferreira}</a> desenvolvido por <a href="https://arferreira.github.io/" class="dotstore-link" target="_blank">Antonio Ricardo.</a></h5>
            </div>
          </div>
        </div>
      </div>
      <!-- Copyright Section Ends -->
      <!-- Back to top Section Begins -->
      <a href="javascript:void(0);" class="back-to-top"><i class="fa fa-long-arrow-up" aria-hidden="true"></i></a>
      <!-- Back to top Section Ends -->
    </div>
  </div>

  <!-- Mobile Menu Section Begins -->
  <div class="main_menucontent overlapblackbg"></div>
  <div class="menu-wrap"></div>
  <!-- Mobile Menu Section Ends -->
  <!-- Jquery Js -->
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Bootstrap Js -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- Modernizr Js -->
  <script type="text/javascript" src="{% static 'js/modernizr.js' %}"></script>
  <!-- Owl Carousel Js -->
  <script type="text/javascript" src="{% static 'js/owl.carousel.js' %}"></script>
  <!-- Localscroll Js -->
  <script type="text/javascript" src="{% static 'js/jquery.localscroll-1.2.7-min.js' %}"></script>
  <!-- Imagesloaded Js -->
  <script type="text/javascript" src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
  <!-- Isotope Js -->
  <script type="text/javascript" src="{% static 'js/jquery.isotope.min.js' %}"></script>
  <!-- Parallax Js -->
  <script type="text/javascript" src="{% static 'js/jquery.parallax-1.1.3.js' %}"></script>
  <!-- Magnific Popup Js -->
  <script type="text/javascript" src="{% static 'js/jquery.magnific-popup.js' %}"></script>
  <!-- Custom Js -->
  <script type="text/javascript" src="{% static 'js/element.js' %}"></script>
</body>

</html>

neulyferreira/frontend/templates/posts/posts.html
{% extends 'base.html' %}
{% block main %}
<div id="main-content" class="content-box right-sidebar pad-top-big pr">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <!-- Blog Post Begins -->
                {% for post in posts %}
                <article class="outer-blog-box pr pad-bottom-small">
                    <div class="blog-img blog-media"><img src="{{ post.image_capa.url }}" alt="images" /></div>
                    <div class="blog-captions">
                        <h2 class="blog-title"> <a href="{% url 'frontend:post_detail' pk=post.pk %}">{{ post.title }}</a> </h2>
                        <ul class="below-blog-list">
                            <li>
                                <a href="javascript:void(0)"> <i class="fa fa-user-o" aria-hidden="true"></i> {{ post.author }} </a>
                            </li>
                            <li>
                                <a href="javascript:void(0)"> <i class="fa fa-calendar-o" aria-hidden="true"></i> {{ post.created_at }} </a>
                            </li>
                            <li>
                                <a href="javascript:void(0)"> <i class="fa fa-heart-o" aria-hidden="true"></i> {{ post.category.title }} </a>
                            </li>
                        </ul>
                        <p>
                            {{ post.content|truncatechars:50|safe }}
                        </p>
                        <div class="bottom-blog">
                            <a href="javascript:void(0)" class="continue-read"> Continuar lendo <i class="fa fa-angle-right" aria-hidden="true"></i> </a>
                            <ul class="social">
                                <li>
                                    <a href="javascript:void(0)"> <i class="fa fa-facebook"></i> </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"> <i class="fa fa-twitter"></i> </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"> <i class="fa fa-google-plus"></i> </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"> <i class="fa fa-linkedin"></i> </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </article>
                {% endfor %}
                <!-- Blog Post Ends -->



                <!-- Blog Pagination Begins -->
                <div class="blog-pagination pad-bottom-small">
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                          {% if posts.has_previous %}
                          <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}"><i class="fa fa-angle-left" aria-hidden="true"></i></a></li>

                            {% endif %}

                              <li class="page-item"><a class="page-link" href="javascript:void(0)">Página {{ posts.number }} de {{ posts.paginator.num_pages }}</a></li>


                            {% if posts.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>

                            {% endif %}

                        </ul>
                    </nav>
                </div>
                <!-- Blog Pagination Ends -->
            </div>
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <div class="sidebar pad-bottom-small">
                    <!-- Search Form Widget Begins -->
                    <div class="widget widget_search">
                        <h2 class="widget-title">Buscar</h2>
                        <form>
                            <input type="text" />
                            <button type="button" class="search-submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                    <!-- Search Form Widget Ends -->
                    <!-- About Widget Begins -->
                    <div class="widget widget_about">
                        <h2 class="widget-title">Meu Resumo</h2>
                        <div class="about-box">
                            <div class="about-img"> <img src="{{ about.image_capa.url }}" alt="images"> </div>
                            <div class="about-info">
                                <p>{{ about.summary | truncatechars:50 }}</p>
                                <ul class="social">
                                    <li>
                                        <a href="https://www.facebook.com/neuly.ferreiradasilva" target="_blank"> <i class="fa fa-facebook"></i> </a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0)"> <i class="fa fa-youtube"></i> </a>
                                    </li>
                                </ul>
                                <a href="{% url 'frontend:about'  %}" class="continue-read">Leia Mais <i class="fa fa-angle-right" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>
                    <!-- About Widget Ends -->
                    <!-- Recent Entry Widget Begins -->
                    <div class="widget widget_recent_entries">
                        <h2 class="widget-title">Últimos Posts</h2>
                        {% for recent_post in recent_posts %}
                        <div class="recent-box">
                            <div class="recent-img"> <img src="{{ recent_post.image_capa.url }}" alt="images"> </div>
                            <div class="about-info recent-info">
                                <h4> <a href="{% url 'frontend:post_detail' pk=recent_post.pk %}">{{ recent_post.title }}</a> </h4>
                                <h5>{{ recent_post.created_at | date:"d F Y" }}</h5>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Recent Entry Widget Ends -->
                    <!-- Categories Widget Begins -->
                  
                    <!-- Categories Widget Ends -->
                    <!-- Ad Banner Widget Begins -->
                    <div class="widget widget_ad_banner">
                        <a href="javascript:void(0)" target="_blank"> <img src="{{ senzala.image.url }}" alt="images" /> </a>
                    </div>
                    <!-- Ad Banner Widget Ends -->
                    <!-- Tag Cloud Widget Begins -->
                    <div class="widget widget_tag_cloud">
                        <h2 class="widget-title">Categorias populares</h2>
                        <div class="popular-box">
                          <ul>
                            {% for category in categories %}
                              <li> <a href="javascript:void(0)">{{ category.title }}</a> </li>
                             {% endfor %}
                          </ul>
                        </div>
                    </div>
                    <!-- Tag Cloud Widget Ends -->
                </div>
            </div>
        </div>
    </div>
</div>

<!-- insta-post Section Begins -->
<div id="insta-post" class="instagram-box pr pad-bottom-big">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <h2> <strong>Publicidade</strong></h2>
            </div>
        </div>
    </div>
    <div class="instagram-feed" id="footer-instagram-feed">
      {% for ad in ads %}
        <div class="item">
            <a href="javascript:void(0)"><img src="{{ ad.image.url }}" alt="{{ ad.title }}"></a>
        </div>
        {% endfor %}
    </div>
</div>
<!-- insta-post Section Ends -->
    {% endblock %}